apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-southeast-2

nodeGroups:
  - name: grupo-minimo
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
