--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster2
  region: ap-southeast-2

nodeGroups:
  - name: ng1-public
    instanceType: t3.micro
    desiredCapacity: 2
  
managedNodeGroups:
  - name: ng2-managed
    instanceType: t2.micro
    minSize: 1
    maxSize: 3
    desiredCapacity: 2  